# Generated by Django 5.0.4 on 2024-05-14 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
