# Generated by Django 5.0.4 on 2024-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
