# Generated by Django 5.0.4 on 2024-05-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0008_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
