# Generated by Django 5.0.4 on 2024-05-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0012_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('user', 'employer')},
        ),
    ]
