# Generated by Django 5.0.4 on 2024-05-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_search', '0013_alter_room_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
    ]
